---
title: "TIPNet long-term dashboard (prototype)"
author: "Corrado Lanera"
date: "Last update `r Sys.Date()`"

output:
    flexdashboard::flex_dashboard:
        social: [ "twitter", "facebook", "menu" ]
        orientation: rows
        vertical_leyout: fill
        navbar:
          - { title: "UBESP", href: "https://ubesp.jimdo.com/" }

runtime: shiny_prerendered

biblio-style: apalike
link-citations: yes
description: "Prototype example for the TIPNet long-term dashboard"
---

```{r, include=FALSE}
options(knitr.duplicate.label = 'allow')
```


```{r setup, include=FALSE}
library(flexdashboard)
# these computing functions are only toy examples
computeArticles = function(...) return(45)
computeComments = function(...) return(126)
computeSpam = function(...) return(15)
```

# General statistics

row
-----------------------------------------------------------------------

### Center involved

```{r}
articles = computeArticles()
valueBox(articles, icon = "fa-pencil")
```

### Record stored

```{r}
comments = computeComments()
valueBox(comments, icon = "fa-comments")
```

### Incomplete data

```{r}
spam = computeSpam()
valueBox(
  spam, icon = "fa-trash",
  color = ifelse(spam > 10, "warning", "primary")
)
```

row
-----------------------------------------------------------------------

### Tab title

foo








# Overall perfomrmance

row
-----------------------------------------------------------------------

### Centers reporting data

```{r}
gauge(91, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Admission per day 

```{r}
gauge(37.4, min = 0, max = 50, gaugeSectors(
  success = c(41, 50), warning = c(21, 40), danger = c(0, 20)
))
```

### Average PIM

```{r}
gauge(7, min = 0, max = 10, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```








# Single chart {data-navmenu="Charts Groups"}

row {data-icon="fa-signal"}
-----------------------------------------------------------------------

### Chart A

```{r, echo=FALSE}
sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r, context="server"}
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```

> Unità di Biostatistica, Epidemiologia, e Sanlute Pubblica --- Dip. Scienze Cardio Toraco Vascolari e Salute Pubblica (Univ. di Padova -- IT)











# Two column charts {data-navmenu="Charts Groups"}

row {data-icon="fa-table"}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```




















# Mixed charts

row {data-icon="fa-signal"}
-----------------------------------------------------------------------

### Chart D

```{r}

```

row {data-icon="fa-table"}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```
