# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


 os:
   - linux
   - osx

matrix:
  include:
  - r: devel
    os: linux # rdevel has problem with rtools in osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
