---
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
runtime: shiny_prerendered
date: "Last update `r Sys.Date()`"
biblio-style: apalike
link-citations: yes

params:
  period: "2010 - 2014"

title: "`r paste0('TIPNet long-term report, years ', params$period)`"
subtitle: "(prototype by Corrado Lanera^[Unità di Biostatistica, Epidemiologia, e Sanlute Pubblica --- Dip. Scienze Cardio Toraco Vascolari e Salute Pubblica (Univ. di Padova -- IT)])"
author: "Italian Pediatric Intensive Care Units Network (TIPNet) in collaboration with Italian Society of Pediatric and Neonatal Anesthesia and Intensive Care (SARNePI) and CINECA"

description: "`r paste0('Prototype example for the TIPNet long-term report (years ', params$period, ')')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r intro, child = '010-intro.Rmd'}
```




# Examples {.tabset .tabset-fade .tabset-pills}

## Example one
```{r, echo=FALSE}
sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r, context="server"}
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```


## Example two
```{r eruptions, echo=FALSE}
selectInput(
  'breaks', label = 'Number of bins:',
  choices = c(10, 20, 35, 50), selected = 20
)
plotOutput("distPlot2")
```


```{r, context="server"}
output$distPlot2 <- renderPlot({
  par(mar = c(4, 4, .1, .5))
  hist(
    faithful$eruptions, as.numeric(input$breaks),
    col = 'gray', border = 'white',
    xlab = 'Duration (minutes)', main = ''
  )
})
```
