--- 
title: "TIPNet long-term report"
subtitle: "(prototype)"
author: "Corrado Lanera^[Unità di Biostatistica, Epidemiologia, e Sanlute Pubblica --- Dip. Scienze Cardio Toraco Vascolari e Salute Pubblica (Univ. di Padova -- IT)]"
date: "Last update `r Sys.Date()`"

output:
  html_document:
    toc: true
    toc_float: true
    number_section: true
    df_print: paged

runtime: shiny_prerendered

biblio-style: apalike
link-citations: yes

description: "Prototype example for the TIPNet long-term report."
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

# Preamble {-}

foo $\frac{1}{2}$

```{r intro, child = '010-intro.Rmd'}
```


# Examples

## Example one
```{r, echo=FALSE}
sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r, context="server"}
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```


## Example two
```{r eruptions, echo=FALSE}
selectInput(
  'breaks', label = 'Number of bins:',
  choices = c(10, 20, 35, 50), selected = 20
)
plotOutput("distPlot2")
```


```{r, context="server"}
output$distPlot2 <- renderPlot({
  par(mar = c(4, 4, .1, .5))
  hist(
    faithful$eruptions, as.numeric(input$breaks),
    col = 'gray', border = 'white',
    xlab = 'Duration (minutes)', main = ''
  )
})
```
# References {-}
```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
