---
params:
    export: FALSE
    breaks: 20

title: "My title"
output: bookdown::html_document2
runtime: shiny_prerendered
---
```{r setup, include=FALSE}
library(tidyverse)
```


### Trends
```{r eruptions, echo=FALSE, eval=!params$export}
selectInput(
  'breaks', label = 'Number of bins:',
  choices = c(10, 20, 35, 50), selected = params$breaks
)
```

```{r euption-output, eval=!params$export, include=!params$export}
plotOutput("distPlot3")
```


```{r, context="server", eval=!params$export, include=!params$export}
output$distPlot3 <- renderPlot({
  par(mar = c(4, 4, .1, .5))
  hist(
    faithful$eruptions, as.numeric(input$breaks),
    col = 'gray', border = 'white',
    xlab = 'Duration (minutes)', main = ''
  )
})
```

```{r, eval=params$export, include=params$export}
par(mar = c(4, 4, .1, .5))
hist(
faithful$eruptions, as.numeric(params$breaks),
col = 'gray', border = 'white',
xlab = 'Duration (minutes)', main = ''
)
```


# Report download

```{r, echo=FALSE, eval=!params$export, include=!params$export}
downloadLink("report", "Generate report")
```

```{r, context="server", eval=!params$export, include=!params$export}
output$report <- downloadHandler("reprex.html",

    content = function(file) {
        tmp_dir <- tempdir()
        tmp_rmd <- file.path(tmp_dir, "reprex.Rmd")
        file.copy("reprex.Rmd", tmp_rmd, overwrite = TRUE)
        
        foo <- read_lines(tmp_rmd) %>% 
            str_replace("^runtime: shiny_prerendered$", "")
        
        write_lines(foo, tmp_rmd)
        params <- list(export = TRUE, breaks = input$breaks)
        
        rmarkdown::render(tmp_rmd, output_file = file,
            # output_options = list(self_contained = TRUE),
            # intermediates_dir = dirname(file),
            # clean = FALSE,
            # runtime = "static",
            params = params,
            envir = new.env(parent = globalenv())
        )
    }
)
```
